# Configure ServiceMesh
#
# - expect own namespace for app
# - register ServiceMeshMemberRoll (expect here high privileges, otherwise use ServiceMeshMember)
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
    # a list of projects joined into the service mesh
    - bookinfo

