# Kustomize: Bookinfo
# https://raw.githubusercontent.com/Maistra/istio/maistra-2.0/samples/bookinfo/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo

resources:
- 010-servicemesh.yaml
- 020-bookinfo-apps.yaml
- 030-bookinfo-gateway.yaml
- 040-bookinfo-destination-rules.yaml