= OpenShift Universe: GitOps with ServiceMesh
:author: Hafid Haddouti
:toc: macro
:toclevels: 4
:sectlinks:
:sectanchors:

GitOps and ServiceMesh

toc::[]

== Overview

Example for GitOps in OpenShift using ServiceMesh and the reference sample app bookinfo.
This repository represents the config repository in GitOps principle.

== Initialization

The initialization installs the ArgoCD project and application. Currently only one application representing the bookinfo components.

----
$ oc apply -f argocd/00-argocd-project.yaml
namespace/bookinfo created
rolebinding.rbac.authorization.k8s.io/bookinfo-role-binding created
rolebinding.rbac.authorization.k8s.io/mesh-users created
appproject.argoproj.io/argocd-team-travel created
application.argoproj.io/argocd-travel-booking created
----

== Configuration

This repository represents the configuration for an IT-System/Application with all relevant components. Any stage/environment specific adjustments will be made here in this config repo.
The ArgoCD config is also dedicated for this application.

== Summary

tbd

== References

N/A

== Open

N/A


== License

This article is licensed under the Apache License, Version 2.
Separate third-party code objects invoked within this code pattern are licensed by their respective providers pursuant
to their own separate licenses. Contributions are subject to the
link:https://developercertificate.org/[Developer Certificate of Origin, Version 1.1] and the
link:https://www.apache.org/licenses/LICENSE-2.0.txt[Apache License, Version 2].

See also link:https://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN[Apache License FAQ]
.
