#
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo
  labels:
    openshift.io/cluster-monitoring: "true"
---
# Logical group for applications
# the config is very generic
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-team-travel
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    # List all namespaces which ArgoCD should watch within this project
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-travel-booking
  namespace: openshift-gitops
spec:
  destination:
    namespace: bookinfo
    server: 'https://kubernetes.default.svc'
  project: argocd-team-travel
  source:
    repoURL: https://github.com/ocp-universe/ocp-servicemesh-bookinfo-config
    targetRevision: main
    path: kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true